name: charts_flutter
version: 0.12.0
description: Material Design charting library for Flutter.

environment:
  sdk: '>=2.12.0 <3.0.0'  # Compatible with Dart 2.18.6

dependencies:
  charts_common: ^0.12.0
  collection: ^1.16.0  # Compatible with Dart 2.18
  flutter:
    sdk: flutter
  intl: ^0.17.0        # Last version compatible with Dart 2
  logging: ^1.0.2
  meta: ^1.7.0         # Last version compatible with Dart 2

dependency_overrides:
  test_api: 0.4.12  # Matches flutter_test dependency
  matcher: 0.12.16
  async: 2.11.0

dev_dependencies:
  mockito: ^5.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  test: 1.24.2  # Use this version to avoid conflicts with flutter_test
